import os
from fpdf import FPDF
from datetime import datetime

# Get the directory where the current script is located
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
# The fonts are downloaded to the trendpilot root
FONT_REGULAR = os.path.join(os.path.dirname(BASE_DIR), "NanumGothic.ttf")
FONT_BOLD = os.path.join(os.path.dirname(BASE_DIR), "NanumGothicBold.ttf")

class StrategyPDF(FPDF):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Add custom font if exists
        try:
            self.add_font('Nanum', '', FONT_REGULAR)
            self.add_font('Nanum', 'B', FONT_BOLD)
        except Exception as e:
            pass

    def header(self):
        try:
            self.set_font('Nanum', 'B', 18)
        except Exception as e:
            self.set_font('Arial', 'B', 18)
            print("Font error:", e)
        
        self.set_text_color(0, 51, 102) # Dark blue
        self.cell(w=0, h=10, text='K-Beauty 글로벌 진출 전략 보고서', border=False, align='C', new_x="LMARGIN", new_y="NEXT")
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        try:
            self.set_font('Nanum', '', 8)
        except:
            self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(w=0, h=10, text=f'Page {self.page_no()} | Generated by TrendPilot', align='C', new_x="LMARGIN", new_y="NEXT")

def create_strategy_pdf(report_data: dict, target_country: str, output_path: str):
    pdf = StrategyPDF()
    pdf.add_page()
    
    try:
        pdf.set_font('Nanum', '', 12)
    except:
        pdf.set_font('Arial', '', 12)

    # 1. Market Feasibility
    pdf.set_font('Nanum', 'B', 14)
    pdf.set_text_color(0, 102, 204)
    pdf.cell(w=0, h=10, text='1. 시장 진입 가능성 (Market Feasibility)', new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font('Nanum', '', 11)
    pdf.set_text_color(0, 0, 0)
    mf = report_data.get('market_feasibility', {})
    pdf.multi_cell(w=0, h=8, text=f"• 타겟 국가: {target_country}", new_x="LMARGIN", new_y="NEXT")
    pdf.multi_cell(w=0, h=8, text=f"• 진입 가능성 점수: {mf.get('score', 'N/A')} / 100", new_x="LMARGIN", new_y="NEXT")
    pdf.multi_cell(w=0, h=8, text=f"• 진입 우선순위: {mf.get('entry_priority', 'N/A')}", new_x="LMARGIN", new_y="NEXT")
    pdf.multi_cell(w=0, h=8, text=f"• 요약: {mf.get('summary', 'N/A')}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # 2. Risk Analysis
    pdf.set_font('Nanum', 'B', 14)
    pdf.set_text_color(0, 102, 204)
    pdf.cell(w=0, h=10, text='2. 리스크 분석 (Risk Analysis)', new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font('Nanum', '', 11)
    pdf.set_text_color(0, 0, 0)
    ra = report_data.get('risk_analysis', {})
    pdf.multi_cell(w=0, h=8, text=f"• 규제 리스크: {ra.get('regulatory', 'N/A')}", new_x="LMARGIN", new_y="NEXT")
    pdf.multi_cell(w=0, h=8, text=f"• 경쟁 리스크: {ra.get('competitive', 'N/A')}", new_x="LMARGIN", new_y="NEXT")
    pdf.multi_cell(w=0, h=8, text=f"• 문화적 리스크: {ra.get('cultural', 'N/A')}", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font('Nanum', 'B', 11)
    pdf.cell(w=0, h=8, text='주요 참고 사항:', new_x="LMARGIN", new_y="NEXT")
    pdf.set_font('Nanum', '', 11)
    for note in ra.get('notes', []):
        pdf.multi_cell(w=0, h=8, text=f"  - {note}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # 3. Differentiation USP
    pdf.set_font('Nanum', 'B', 14)
    pdf.set_text_color(0, 102, 204)
    pdf.cell(w=0, h=10, text='3. 핵심 소구점 (Differentiation USP)', new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font('Nanum', '', 11)
    pdf.set_text_color(0, 0, 0)
    usps = report_data.get('differentiation_usp', [])
    for u in usps:
        pdf.set_font('Nanum', 'B', 11)
        pdf.multi_cell(w=0, h=8, text=f"• {u.get('usp', '')}", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font('Nanum', '', 11)
        for ev in u.get('evidence_refs', []):
            pdf.multi_cell(w=0, h=8, text=f"  [근거] {ev}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # 4. Price Positioning
    pdf.set_font('Nanum', 'B', 14)
    pdf.set_text_color(0, 102, 204)
    pdf.cell(w=0, h=10, text='4. 가격 포지셔닝 (Price Positioning)', new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font('Nanum', '', 11)
    pdf.set_text_color(0, 0, 0)
    pp = report_data.get('price_positioning', {})
    pdf.multi_cell(w=0, h=8, text=f"• 전략: {pp.get('strategy', 'N/A')}", new_x="LMARGIN", new_y="NEXT")
    pdf.multi_cell(w=0, h=8, text=f"• 권장 가격대: {pp.get('recommended_range', 'N/A')}", new_x="LMARGIN", new_y="NEXT")
    pdf.multi_cell(w=0, h=8, text=f"• 논리/근거: {pp.get('rationale', 'N/A')}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # 5. Messaging Direction
    pdf.set_font('Nanum', 'B', 14)
    pdf.set_text_color(0, 102, 204)
    pdf.cell(w=0, h=10, text='5. 마케팅 메시지 방향성 (Messaging Direction)', new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font('Nanum', '', 11)
    pdf.set_text_color(0, 0, 0)
    md = report_data.get('messaging_direction', {})
    
    pdf.set_font('Nanum', 'B', 11)
    pdf.cell(w=0, h=8, text='• 메시지 톤 (Tone):', new_x="LMARGIN", new_y="NEXT")
    pdf.set_font('Nanum', '', 11)
    pdf.multi_cell(w=0, h=8, text=f"  {', '.join(md.get('tone', []))}", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font('Nanum', 'B', 11)
    pdf.cell(w=0, h=8, text='• 권장 (DO):', new_x="LMARGIN", new_y="NEXT")
    pdf.set_font('Nanum', '', 11)
    for do_item in md.get('do', []):
        pdf.multi_cell(w=0, h=8, text=f"  - {do_item}", new_x="LMARGIN", new_y="NEXT")
        
    pdf.set_font('Nanum', 'B', 11)
    pdf.cell(w=0, h=8, text='• 지양 (DON\'T):', new_x="LMARGIN", new_y="NEXT")
    pdf.set_font('Nanum', '', 11)
    for dont_item in md.get('dont', []):
        pdf.multi_cell(w=0, h=8, text=f"  - {dont_item}", new_x="LMARGIN", new_y="NEXT")
        
    pdf.set_font('Nanum', 'B', 11)
    pdf.cell(w=0, h=8, text='• 마케팅 훅 예시 (Example Hooks):', new_x="LMARGIN", new_y="NEXT")
    pdf.set_font('Nanum', '', 11)
    for hook in md.get('example_hooks', []):
        pdf.multi_cell(w=0, h=8, text=f"  - \"{hook}\"", new_x="LMARGIN", new_y="NEXT")

    pdf.output(output_path)
    return output_path

